general:
  id: '1'
  platform: local
  date: 2023-09-25 14:47
  node_list: null
  tasks: '232'
  nodes: null
benchmark:
  name: Cube with imbalanced domain decomposition
  version: 1.0
  git_commit: 128f0b4fb4cbe0b9473e670e810e6dedfe66a09f
  git_origin: git@github.com:Yelvd/Hemocell-Performance-Benchmarks.git
hemocell:
  git_commit: 0ffb27cc78c4ea5ab4568f76457b428521d094e1
  git_origin: git@github.com:UvaCsl/HemoCell-dev.git
  version: v2.6
ear:
  policy: monitoring
